name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm i -g vite
        npm run preview -- --port 8080 --host 0.0.0.0 &
    - name: Esperar a que el servidor responda
      run: npx wait-on http://localhost:8080 --timeout 60000
    - name: Crear túnel público con Ngrok
      uses: shogo82148/actions-ngrok@v1
      with:
          ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
          tunnel_type: http
          tunnel_port: 8080
